name: readthedocs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - interpolation=2.2.6
  - numbalsoda=0.3.5
  - numpy=1.26.4
  - scipy=1.13.1
  - sphinx_gallery
  - sphinx_rtd_theme
  - myst-parser
  - sphinx-autoapi
  - sphinxcontrib-bibtex
