name: readthedocs
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10, <3.12
  - interpolation>=2.2.6
  - numbalsoda
  - numba
  - numpy
  - scipy
  - contourpy
  - sphinx_rtd_theme
  - myst-parser
  - sphinx-autoapi
  - sphinxcontrib-bibtex
  - pip  
  - pip:
    - sphinx_gallery
